apiVersion: v1
kind: Service
metadata:
    name: "tamirautoinstrum-30a9"
    labels:
        app: "tamirautoinstrum-30a9"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "tamirautoinstrum-30a9"